baseurl = "/"
title = "Mutex Control"
languageCode = "en-us"
paginate = "10"         # Number of posts per page
theme = "mainroad"

[Author]
name = "Aung Khant Maw"
bio = "Passionate Embedded Systems Engineer."
avatar = "images/avatar.png"

[Params]
description = "Internet of Things (IoT), AI, and Firmware Engineering" # Description of your site
opengraph = true
twitter_cards = false
readmore = true                                                        # Show "Read more" button in list if true
authorbox = true
pager = true
post_meta = ["date", "categories"]                                     # Order of post meta information
mainSections = ["post", "docs"]
schema = true

[Params.logo]
subtitle = "Building Blocks of Tomorrow: Embedded Systems Unveiled" # Logo subtitle

[Params.sidebar]
home = "right"   # Configure layout for home page
list = "right"   # Configure layout for list pages
single = "right" # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
recent_num = 5       # Set the number of articles in the "Recent articles" widget
tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static/images'
target = 'assets/images'
